# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    insecure-external-code-execution: allow
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "Europe/Warsaw"
    registries:
      - artifactory
    directory: "/" # Location of package manifests
    commit-message:
      prefix: "MFD-5939: Bump versions\n\nfeature:"
    groups:
      break:
        patterns: ["p.*"]
        applies-to: version-updates
        update-types:
        - "major"
      feature-fix:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"

registries:
  artifactory:
    type: "python-index"
    url: "https://ubit-artifactory-or.intel.com/artifactory/api/pypi/epg-sw-mfd-or-repos/simple"
