# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
- package-ecosystem: "pip" # See documentation for possible values
  insecure-external-code-execution: allow
  open-pull-requests-limit: 0   
  schedule:
    interval: daily
  directory: "/" # Location of package manifests
  commit-message:
    prefix: "MFD-5098: Security vulnerability\n\n feature:"
