name: PR Conventional Commit Validation
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  validate-pr-title:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'false'