name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:    
    runs-on: dependabot    
    
    steps:
    - name: Update PR Description
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          const newDescription = 'JIRA PR';

          await github.rest.pulls.update({
            owner,
            repo,
            pull_number: issue_number,
            body: newDescription
          });
