name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:    
    runs-on: dependabot    
    
    steps:
    - name: test
      run: |
        echo ${{ github.actor }}
    - name: Update PR Description
      if: github.actor == 'dependabot'
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          const newDescription = 'Your new PR description here';

          await github.rest.pulls.update({
            owner,
            repo,
            pull_number: issue_number,
            body: newDescription
          });
