name: Run action to update PR
on:
  pull_request:
    types: [opened, reopened]

jobs:
  trigger-dispatch:
    runs-on: dependabot
    steps:
    - name: Send repository_dispatch event
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          await github.rest.repos.createDispatchEvent({
            owner: 'intel-sandbox',
            repo: 'libraries.python.mfd.mfd-testing',
            event_type: 'update-pr',
            client_payload: {
              pr_title: pr.title,
              pr_body: pr.body,
              pr_html: pr.html_url,
              repo_name: pr.base.repo.name.split('.'),
              owner: context.repo.owner,
              repo: context.repo.repo,
              pr_number: pr.number,
              head_ref: '${{ github.head_ref }}'
            }
          });
