name: Update PR to met autoversioning
on: 
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: dependabot

    steps:
    - name: Create JIRA ticket and PR update
      uses: actions/github-script@v6
      id: jira-ticket
      env:
        JIRA_URL: https://jira.devtools.intel.com
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/intel_CA_chain.crt
      with:
        result-encoding: string
        script: |
          const pr = context.payload.pull_request;
          const title = pr.title;
          const description = pr.body;
          const jiraUrl = process.env.JIRA_URL;
          const token = process.env.JIRA_API_TOKEN;
          const branchName = context.payload.pull_request.head.ref;

          const data = {
            "fields": {
              "project": {
                "id": "114600"
              },
              "summary": title,
              "description": description,
              "issuetype": {
                "id": "12"
              },
              "components": [
                {
                    "name": "_team_only_"
                }
              ]
            }
          };

          console.log(data)

          const response = await fetch(`${jiraUrl}/rest/api/2/issue`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(data)
          });
          if (!response.ok) {
            console.error(`Response status: ${response.status}`);
            const text = await response.text();
            console.error(`Response body: ${text}`);
            throw new Error('Failed to create JIRA issue');
          }
          const jira_response = await response.json();
          const jira_ticket_id = jira_response.key
          console.log(`Created issue: ${jira_ticket_id}`);
          const new_title = `${jira_ticket_id}: ${title}`
          const new_commit_desc = `${new_title}\nfeature: ${title}`
          console.log(new_title)
          console.log(new_commit_desc)

          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.number,
            title: new_title,
            body: description
          });
          return new_commit_desc

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Update commit
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git commit --amend -m '${{ steps.jira-ticket.outputs.result }}'
        git push -f origin HEAD
