name: Update PR to met autoversioning

on:
  workflow_call:
    inputs:
      PREFIX_SECRET_PATH:
        description: 'Prefix based on IT’s deployment of the CyberArk infrastructure'
        required: false
        default: 'FMSPAMVLT101/LOBUSER_prapp'
        type: string
      AAM_SAFE:
        required: false
        type: string
        description: "AAM Safe Name where secrets are stored"
        default: 'AAM-PR-40726-GHAMFDSAFE'
      HOST_ID:
        required: true
        type: string
        description: "HOST_ID value retrieved from IT ticket"
      GH_TOKEN_AAM_ACCOUNT_NAME:
        required: false
        type: string
        description: "Github token AAM Account name"
        default: 'Operating System-UnmanagedAccounts-AllOSs-sys_ptmfd_github_token'
      JIRA_TOKEN_AAM_ACCOUNT_NAME:
        required: false
        type: string
        description: "Jira token AAM Account name"
        default: 'Operating System-UnmanagedAccounts-AllOSs-sys_ptmfd_jira_token'
      ENVIRONMENT:
        type: string
        required: false
        default: 'production'

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  dependabot:
    runs-on: dependabot
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - uses: intel-innersource/frameworks.actions.certs@latest
    - name: Pre Step - get secrets from AAM
      uses: intel-innersource/frameworks.actions.conjur-fetch@master
      with:
        host_id: ${{ inputs.HOST_ID }}
        secrets: >
          ${{ inputs.PREFIX_SECRET_PATH }}/${{ inputs.AAM_SAFE }}/${{ inputs.JIRA_TOKEN_AAM_ACCOUNT_NAME }}/password|JIRA_TOKEN;
          ${{ inputs.PREFIX_SECRET_PATH }}/${{ inputs.AAM_SAFE }}/${{ inputs.GH_TOKEN_AAM_ACCOUNT_NAME }}/password|GH_TOKEN
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm install sanitize-html
    - name: Create JIRA ticket and PR update
      uses: actions/github-script@v7
      id: jira-ticket
      env:
        JIRA_URL: https://jira.devtools.intel.com
        NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/intel_CA_chain.crt
      with:
        result-encoding: string
        script: |
          const pr = context.payload.pull_request;
          const title = pr.title;
          const description = pr.body;
          const pr_html = pr.html_url;
          const jira_html = process.env.JIRA_URL;
          const token = process.env.JIRA_TOKEN;
          const repo_name_split = pr.base.repo.name.split('.');
          const sanitizeHtml = require('sanitize-html');
          const desciption_no_html_tags = sanitizeHtml(description, {
            allowedTags: [],
            allowedAttributes: {}
          });

          const data = {
            "fields": {
              project: {
                "id": "114600"
              },
              summary: title,
              description: `[${title}|${pr_html}]\n${desciption_no_html_tags}`,
              issuetype: {
                id: "12"
              },
              components: [
                {
                    name: "_team_only_"
                }
              ]
            }
          };

          const response = await fetch(`${jira_html}/rest/api/2/issue`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(data)
          });
          if (!response.ok) {
            console.error(`Response status: ${response.status}`);
            const text = await response.text();
            console.error(`Response body: ${text}`);
            throw new Error('Failed to create JIRA issue');
          }
          const jira_response = await response.json();
          const jira_ticket_id = jira_response.key
          console.log(`Created issue: ${jira_ticket_id}`);
          const new_title = `${jira_ticket_id}: ${title}`;
          const new_commit_desc = `${new_title}\n\nfeature: ${title}`;

          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.number,
            title: new_title,
            body: description
          });
          return new_commit_desc;

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ env.GH_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Update commit
      run: |
        git commit --amend -m '${{ steps.jira-ticket.outputs.result }}'
        git push -f origin HEAD