name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: dependabot

    steps:
    - name: Create Jira ticket
      uses: actions/github-script@v6
      env:
        JIRA_URL: https://jira.devtools.intel.com/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_USER_EMAIL: piotr.maruszewski@example.com
      with:
        script: |
          const pr = context.payload.pull_request;
          const title = pr.title;
          const description = pr.body;

          const axios = require('axios');

          const jiraUrl = process.env.JIRA_URL;
          const user = process.env.JIRA_USER_EMAIL;
          const token = process.env.JIRA_API_TOKEN;

          const auth = Buffer.from(`${user}:${token}`).toString('base64');

          const headers = {
            'Authorization': `Basic ${auth}`,
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          };

          const data = {
            fields: {
              project: {
                key: "MFD"
              },
              summary: title,
              description: description,
              issuetype: {
                name: "Story"
              }
            }
          };

          axios({
            method: 'post',
            url: `${jiraUrl}/rest/api/3/issue/`,
            headers: headers,
            data: data
          })
          .then(response => {
            console.log(`Created issue: ${response.data.key}`);
          })
          .catch(error => {
            console.error("Error creating issue:", error);
          });
