name: CI BUILD

on:
  push:
    branches:
      - main

jobs:
  build_upload_whl:
    strategy:
      matrix:
        include:
          - name: python-version-3-10
            python_version: '3.10'
            push_tag: false
            continue-on-error: true
          - name: python-version-3-13
            python_version: '3.13'
            push_tag: false
            continue-on-error: true
    uses: ./.github/workflows/build_upload_whl.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      PUSH_TAG: ${{ matrix.push_tag }}
      RELEASE_BUILD: true
      GIT_USER: 'sys_ptmfd'
      GIT_EMAIL: 'sys_ptmfd@intel.com'
      PROJECT_NAME: 'mfd-testing'
      RUNS_ON: "sandbox.prod.amr.dind"
