name: CI BUILD

on:
  push:
    branches:
      - main

jobs:
  build_whl:
    strategy:
      matrix:
        python_version: ['3.10', '3.13']
    uses: ./.github/workflows/build_upload_whl.yml
    continue-on-error: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      RELEASE_BUILD: true
      GIT_USER: 'pmarusze'
      GIT_EMAIL: 'piotr.maruszewski@intel.com'
      PROJECT_NAME: 'mfd-testing'
      RUNS_ON: "ubuntu-latest"
