name: CI BUILD

on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ["sandbox.prod.amr.dind"]
    env:
      GIT_AUTHOR_NAME: sys-ptipu
      GIT_AUTHOR_EMAIL: sys_ptipu@intel.com
      GIT_COMMITTER_NAME: sys-ptipu
      GIT_COMMITTER_EMAIL: sys_ptipu@intel.com
    steps:
    - uses: actions/checkout@v4
      with:
        path: src

    - uses: actions/checkout@v4
      with:
        repository: intel-innersource/libraries.python.mfd.mfd-utils
        path: mfd-utils
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.11'
        cache: 'pip' # caching pip dependencies

    - name: Version bumping
      id: VERSION_BUMP
      run: |
        python -m venv bump_version
        source bump_version/bin/activate
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/mfd-utils
        pip install python-semantic-release==7.34.6
        pip install urllib3==1.26.15
        pip install -r src/requirements-dev.txt
        mfd-create-config-files --project-dir src
        cd src
        cat pyproject.toml
        ../bump_version/bin/semantic-release print-version
        version_after_bump=$(semantic-release print-version | tail -n 1 | tr -d '\n')
        echo "Version after semantic-release bump is: ${version_after_bump}"
        semantic-release version
        echo "version_after_bump=v${version_after_bump}" >> $GITHUB_OUTPUT


    - name: Create virtual environment for whl creation
      run: |
        python -m venv whl_creation
        source whl_creation/bin/activate
        pip install build==1.2.2.post1
        cd src
        ../whl_creation/bin/python -m build --wheel --outdir ../whl_creation/dist
        ls -l ../whl_creation/dist

    - name: Push git tag after version bump
      if: success()  # Only run if previous steps succeeded
      run: |
        git push origin "v${version_after_bump}"
      env:
        version_after_bump: ${{ steps.VERSION_BUMP.outputs.version_after_bump }}
