
name: CI BUILD - RELEASE MODE

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: 'GitHub token for authentication'
        required: true
      PYPI_TOKEN:
        description: 'PyPI API token to publish package'
        required: true
    inputs:
      RELEASE_STEPS:
        description: 'Should the package be uploaded to PyPI?'
        required: true
        default: true
        type: boolean
      REPOSITORY_NAME:
        description: 'Repository name'
        required: false
        type: string
      BRANCH_NAME:
        description: 'Branch name to checkout'
        required: true
        type: string
      PYTHON_VERSION:
        description: 'Python version to use'
        required: false
        default: '3.10.11'
        type: string
      PROJECT_NAME:
        description: 'Project name for tests'
        required: true
        type: string
      RUNS_ON:
        description: 'Runner type for the job'
        required: false
        default: 'ubuntu-latest'
        type: string
      TAG_SHA:
        description: 'SHA of the commit to tag'
        required: true
        type: string

jobs:
  build_upload_whl:
    uses: ./.github/workflows/build_upload_whl.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ inputs.REPOSITORY_NAME }}
      BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
      PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}
      RELEASE_BUILD: true
      RELEASE_STEPS: ${{ inputs.RELEASE_STEPS }}
      PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
  push_tag:
    needs: build_upload_whl
    if: ${{ inputs.RELEASE_STEPS }}
    uses: pmarusz/mfd-common/.github/workflows/push_tag.yml@main
    with:
      TAG_VERSION: ${{ needs.build_upload_whl.outputs.version_after_bump }}
      TAG_SHA: ${{ inputs.TAG_SHA }}
