name: DEV BUILD

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_whl:
    strategy:
      matrix:
        include:
          - name: python-version-3-10
            python_version: '3.10'
          - name: python-version-3-13
            python_version: '3.13'
    uses: ./.github/workflows/build_upload_whl.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.head_ref }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      PUSH_TAG: ${{ matrix.push_tag }}
      RELEASE_BUILD: false
      GIT_USER: 'pmarusze'
      GIT_EMAIL: 'piotr.maruszewski@intel.com'
      PROJECT_NAME: 'mfd-testing'
      RUNS_ON: "ubuntu-latest"