name: Push tag

on:
  workflow_call:
    inputs:
      TAG_VERSION:
        required: true
        type: string
      RUNS_ON:
        required: false
        type: string
        default: "ubuntu-latest"
      GIT_USER:
        required: true
        type: string
      GIT_EMAIL:
        required: true
        type: string

jobs:
  unit_tests:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
    - name: Push git tag after version bump
      env:
        GIT_AUTHOR_NAME: ${{ inputs.GIT_USER }}
        GIT_AUTHOR_EMAIL: ${{ inputs.GIT_EMAIL }}
        GIT_COMMITTER_NAME: ${{ inputs.GIT_USER  }}
        GIT_COMMITTER_EMAIL: ${{ inputs.GIT_EMAIL }}
      run: |
        git tag ${{ inputs.TAG_VERSION }}
        git push origin "${{ inputs.TAG_VERSION }}"
