name: Run Tests (UT + FT)


on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  get_tests_to_run:
    runs-on: "ubuntu-latest"
    outputs:
      run_unit_tests: ${{ steps.tests_path_existance.outputs.run_unit_tests }}
      run_functional_tests: ${{ steps.tests_path_existance.outputs.run_functional_tests }}
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
    - name: Determine if unit and functional tests should run
      id: tests_path_existance
      shell: bash
      run: |
          ls -la
          UNIT_TEST_DIR="tests/unit/test_$(echo "${{ github.event.repository.name }}" | tr '-' '_')"
          FUNC_TEST_DIR="tests/system/test_$(echo "${{ github.event.repository.name }}" | tr '-' '_')"

          if [ -d "$UNIT_TEST_DIR" ]; then
          echo "Unit tests directory exists: $UNIT_TEST_DIR"
          echo "run_unit_tests=true" >> $GITHUB_OUTPUT
          else
          echo "Unit tests directory does not exist: $UNIT_TEST_DIR"
          echo "run_unit_tests=false" >> $GITHUB_OUTPUT
          fi

          if [ -d "$FUNC_TEST_DIR" ]; then
          echo "Functional tests directory exists: $FUNC_TEST_DIR"
          echo "run_functional_tests=true" >> $GITHUB_OUTPUT
          else
          echo "Functional tests directory does not exist: $FUNC_TEST_DIR"
          echo "run_functional_tests=false" >> $GITHUB_OUTPUT
          fi

  run_ft_tests:
    name: run_ft_tests_${{ matrix.os }}
    needs: get_tests_to_run
    if: ${{ needs.get_tests_to_run.outputs.run_functional_tests == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: ['3.10', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip install -r requirements-dev.txt
        pip install -r requirements.txt

    - name: Run Functional Tests
      shell: bash
      run: |
        mfd-system-tests --project-dir .

  run_ut_tests_linux:
    name: run_ut_tests_${{ matrix.os }}
    needs: get_tests_to_run
    if: ${{ needs.get_tests_to_run.outputs.run_unit_tests == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: ['3.10', '3.13']
        include:
          - python_version: '3.13'
          - python_version: '3.10'
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip install -r requirements-dev.txt
        pip install -r requirements.txt

    - name: Run Unit Tests
      shell: bash
      run: |
        mfd-unit-tests --project-dir .