name: Run Tests (UT + FT)

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: 'GitHub token for authentication'
        required: true
    inputs:
      PYTHON_VERSION:
        description: 'Python version to use'
        required: false
        default: '3.10.11'
        type: string
      PROJECT_NAME:
        description: 'Project name for tests'
        required: true
        type: string
      RUNS_ON:
        description: 'Runner type for the job'
        required: false
        default: 'ubuntu-latest'
        type: string

jobs:
  get_tests_to_run:
    runs-on: "ubuntu-latest"
    outputs:
      run_unit_tests: ${{ steps.tests_path_existance.outputs.run_unit_tests }}
      run_functional_tests: ${{ steps.tests_path_existance.outputs.run_functional_tests }}
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
    - name: Determine if unit and functional tests should run
      id: tests_path_existance
      shell: bash
      run: |
          ls -la
          UNIT_TEST_DIR="tests/unit/test_$(echo "${{ inputs.PROJECT_NAME }}" | tr '-' '_')"
          FUNC_TEST_DIR="tests/system/test_$(echo "${{ inputs.PROJECT_NAME }}" | tr '-' '_')"

          if [ -d "$UNIT_TEST_DIR" ]; then
          echo "Unit tests directory exists: $UNIT_TEST_DIR"
          echo "run_unit_tests=true" >> $GITHUB_OUTPUT
          else
          echo "Unit tests directory does not exist: $UNIT_TEST_DIR"
          echo "run_unit_tests=false" >> $GITHUB_OUTPUT
          fi

          if [ -d "$FUNC_TEST_DIR" ]; then
          echo "Functional tests directory exists: $FUNC_TEST_DIR"
          echo "run_functional_tests=true" >> $GITHUB_OUTPUT
          else
          echo "Functional tests directory does not exist: $FUNC_TEST_DIR"
          echo "run_functional_tests=false" >> $GITHUB_OUTPUT
          fi

  run_ft_tests:
    name: run_ft_tests_${{ inputs.RUNS_ON }}
    needs: get_tests_to_run
    if: ${{ needs.get_tests_to_run.outputs.run_functional_tests == 'true' }}
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        repository: pmarusz/mfd-common
        ref: main
        token: ${{ secrets.GH_TOKEN }}
        path: common_actions
    - uses: ./common_actions/.github/prepare_test_env
      with:
        PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}
    - name: Run Functional Tests
      shell: bash
      run: |
        mfd-system-tests --project-dir .

  run_ut_linux:
    name: run_ut_tests_${{ inputs.RUNS_ON }}
    needs: get_tests_to_run
    if: ${{ needs.get_tests_to_run.outputs.run_unit_tests == 'true' }}
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        repository: pmarusz/mfd-common
        ref: main
        token: ${{ secrets.GH_TOKEN }}
        path: common_actions
    - uses: ./common_actions/.github/prepare_test_env
      with:
        PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}
    - name: Run Unit Tests
      shell: bash
      run: |
        mfd-unit-tests --project-dir .