name: Run Tests (UT + FT)


on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  get_tests_to_run:
    runs-on: "sandbox.prod.amr.dind"
    outputs:
      run_unit_tests: ${{ steps.tests_path_existance.outputs.run_unit_tests }}
      run_functional_tests: ${{ steps.tests_path_existance.outputs.run_functional_tests }}
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
    - name: Determine if unit and functional tests should run
      id: tests_path_existance
      shell: bash
      run: |
          ls -la
          UNIT_TEST_DIR="tests/unit/test_$(echo "${{ inputs.PROJECT_NAME }}" | tr '-' '_')"
          FUNC_TEST_DIR="tests/system/test_$(echo "${{ inputs.PROJECT_NAME }}" | tr '-' '_')"

          if [ -d "$UNIT_TEST_DIR" ]; then
          echo "Unit tests directory exists: $UNIT_TEST_DIR"
          echo "run_unit_tests=true" >> $GITHUB_OUTPUT
          else
          echo "Unit tests directory does not exist: $UNIT_TEST_DIR"
          echo "run_unit_tests=false" >> $GITHUB_OUTPUT
          fi

          if [ -d "$FUNC_TEST_DIR" ]; then
          echo "Functional tests directory exists: $FUNC_TEST_DIR"
          echo "run_functional_tests=true" >> $GITHUB_OUTPUT
          else
          echo "Functional tests directory does not exist: $FUNC_TEST_DIR"
          echo "run_functional_tests=false" >> $GITHUB_OUTPUT
          fi
  run_tests_linux:
    needs: get_tests_to_run
    strategy:
      matrix:
        os: [sandbox.prod.amr.dind, windows-latest]
        python_version: ['3.10', '3.13']
        include:
          - python_version: '3.13'
            continue-on-error: true
          - python_version: '3.10'
            continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get vars
      run: |
        echo "Run ut=${{ needs.jobs.get_tests_to_run.outputs.run_unit_tests }} "
        echo "Run ft=${{ needs.jobs.get_tests_to_run.outputs.run_functional_tests }} "


    - name: Run UT
      if: ${{ needs.jobs.get_tests_to_run.outputs.run_unit_tests == 'true' }}
      uses: ./.github/tests_actions/linux_ut_tests.yml
      with:
        PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}
    - name: Run FT
      if: ${{ needs.jobs.get_tests_to_run.outputs.run_functional_tests == 'true' }}
      uses: ./.github/tests_actions/linux_ft_tests.yml
      with:
        PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}
