name: 'Prepare test environment'
inputs:
  PYTHON_VERSION:
    description: 'Python version to use'
    required: true
  SOURCE_PATH:
    description: 'Path to the source code directory'
    required: false
    default: 'src'
    type: string
runs:
  using: "composite"
  steps:
  - name: Checkout main repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.PYTHON_VERSION }}
      cache: 'pip'
      path: ${{ inputs.SOURCE_PATH }}

  - name: Install dependencies
    shell: bash
    run: |
      cd ${{ inputs.SOURCE_PATH }}
      python -m pip install --upgrade pip
      pip install -r requirements-test.txt
      pip install -r requirements-dev.txt
      pip install -r requirements.txt