name: 'Prepare test environment'
inputs:
  PYTHON_VERSION:
    description: 'Python version to use'
    required: true
runs:
  using: "composite"
  steps:
  - name: Checkout main repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.PYTHON_VERSION }}
      cache: 'pip'

  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements-test.txt
      pip install -r requirements-dev.txt
      pip install -r requirements.txt